*https://www.rosettacode.org/wiki/Visualize_a_tree (fix ?error C3779: 'Node::tree_indent': a function that returns 'auto' cannot be used before it is defined?)